### ISSUE TITLE
JBAS011048: Failed to construct component instance in picketlink-authorization-idm-jpa-with-subsystem with WildFly 8.1.0

### ISSUE THREAD

**Issue by wcomnisky** [jboss-developer/jboss-picketlink-quickstarts#36]
Project: **picketlink-authorization-idm-jpa-with-subsystem**
Tag: **v2.7.0.Final**

WildFly version: **8.1.0-Final**

Log detail:
<pre>
23:48:36,091 INFO  [org.jboss.as] (Controller Boot Thread) JBAS015874: WildFly 8.1.0.Final "Kenny" started in 7135ms - Started 404 of 463 services (101 services are lazy, passive or on-demand)
23:48:57,162 INFO  [org.jboss.as.repository] (management-handler-thread - 1) JBAS014900: Content added at location C:\eclipse-workspace\picketlink\wildfly-8.1.0.Final\standalone\data\content\fd\86131c9ae03d9b6761979cb23dfdd4f4c465ae\content
23:48:57,167 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-1) JBAS015876: Starting deployment of "picketlink-authorization-idm-jpa-with-subsystem.war" (runtime-name: "picketlink-authorization-idm-jpa-with-subsystem.war")
23:48:57,253 INFO  [org.jboss.as.connector.subsystems.datasources] (MSC service thread 1-6) JBAS010400: Bound data source [java:jboss/datasources/PicketLinkQuickstartDS]
23:48:57,264 INFO  [org.jboss.weld.deployer] (MSC service thread 1-7) JBAS016002: Processing weld deployment picketlink-authorization-idm-jpa-with-subsystem.war
23:48:57,300 INFO  [org.jboss.as.ejb3.deployment.processors.EjbJndiBindingsDeploymentUnitProcessor] (MSC service thread 1-7) JNDI bindings for session bean named LoginController in deployment unit deployment "picketlink-authorization-idm-jpa-with-subsystem.war" are as follows:

        java:global/picketlink-authorization-idm-jpa-with-subsystem/LoginController!org.jboss.as.quickstarts.picketlink.authorization.idm.jpa.LoginController
        java:app/picketlink-authorization-idm-jpa-with-subsystem/LoginController!org.jboss.as.quickstarts.picketlink.authorization.idm.jpa.LoginController
        java:module/LoginController!org.jboss.as.quickstarts.picketlink.authorization.idm.jpa.LoginController
        java:global/picketlink-authorization-idm-jpa-with-subsystem/LoginController
        java:app/picketlink-authorization-idm-jpa-with-subsystem/LoginController
        java:module/LoginController

23:48:57,302 INFO  [org.jboss.as.ejb3.deployment.processors.EjbJndiBindingsDeploymentUnitProcessor] (MSC service thread 1-7) JNDI bindings for session bean named SecurityInitializer in deployment unit deployment "picketlink-authorization-idm-jpa-with-subsystem.war" are as follows:

        java:global/picketlink-authorization-idm-jpa-with-subsystem/SecurityInitializer!org.jboss.as.quickstarts.picketlink.authorization.idm.jpa.SecurityInitializer
        java:app/picketlink-authorization-idm-jpa-with-subsystem/SecurityInitializer!org.jboss.as.quickstarts.picketlink.authorization.idm.jpa.SecurityInitializer
        java:module/SecurityInitializer!org.jboss.as.quickstarts.picketlink.authorization.idm.jpa.SecurityInitializer
        java:global/picketlink-authorization-idm-jpa-with-subsystem/SecurityInitializer
        java:app/picketlink-authorization-idm-jpa-with-subsystem/SecurityInitializer
        java:module/SecurityInitializer

23:48:57,305 INFO  [org.jboss.as.ejb3.deployment.processors.EjbJndiBindingsDeploymentUnitProcessor] (MSC service thread 1-7) JNDI bindings for session bean named AuthorizationChecker in deployment unit deployment "picketlink-authorization-idm-jpa-with-subsystem.war" are as follows:

        java:global/picketlink-authorization-idm-jpa-with-subsystem/AuthorizationChecker!org.jboss.as.quickstarts.picketlink.authorization.idm.jpa.AuthorizationChecker
        java:app/picketlink-authorization-idm-jpa-with-subsystem/AuthorizationChecker!org.jboss.as.quickstarts.picketlink.authorization.idm.jpa.AuthorizationChecker
        java:module/AuthorizationChecker!org.jboss.as.quickstarts.picketlink.authorization.idm.jpa.AuthorizationChecker
        java:global/picketlink-authorization-idm-jpa-with-subsystem/AuthorizationChecker
        java:app/picketlink-authorization-idm-jpa-with-subsystem/AuthorizationChecker
        java:module/AuthorizationChecker

23:48:57,345 INFO  [org.jboss.weld.deployer] (MSC service thread 1-15) JBAS016005: Starting Services for CDI deployment: picketlink-authorization-idm-jpa-with-subsystem.war
23:48:57,351 INFO  [org.jboss.weld.deployer] (MSC service thread 1-14) JBAS016008: Starting weld service for deployment picketlink-authorization-idm-jpa-with-subsystem.war
23:48:57,372 WARN  [org.jboss.weld.Event] (MSC service thread 1-3) WELD-000411: Observer method [BackedAnnotatedMethod] public org.picketlink.internal.IdentityStoreAutoConfiguration.processAnnotatedType(@Observes ProcessAnnotatedType<Object>, BeanManager) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
23:48:57,608 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 64) MSC000001: Failed to start service jboss.deployment.unit."picketlink-authorization-idm-jpa-with-subsystem.war".component.SecurityInitializer.START: org.jboss.msc.service.StartException in service jboss.deployment.unit."picketlink-authorization-idm-jpa-with-subsystem.war".component.SecurityInitializer.START: java.lang.IllegalStateException: JBAS011048: Failed to construct component instance
        at org.jboss.as.ee.component.ComponentStartService$1.run(ComponentStartService.java:57) [wildfly-ee-8.1.0.Final.jar:8.1.0.Final]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [rt.jar:1.8.0_45]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [rt.jar:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [rt.jar:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [rt.jar:1.8.0_45]
        at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_45]
        at org.jboss.threads.JBossThread.run(JBossThread.java:122)
Caused by: java.lang.IllegalStateException: JBAS011048: Failed to construct component instance
        at org.jboss.as.ee.component.BasicComponent.constructComponentInstance(BasicComponent.java:162) [wildfly-ee-8.1.0.Final.jar:8.1.0.Final]
        at org.jboss.as.ee.component.BasicComponent.constructComponentInstance(BasicComponent.java:133) [wildfly-ee-8.1.0.Final.jar:8.1.0.Final]
        at org.jboss.as.ee.component.BasicComponent.createInstance(BasicComponent.java:89) [wildfly-ee-8.1.0.Final.jar:8.1.0.Final]
        at org.jboss.as.ejb3.component.singleton.SingletonComponent.getComponentInstance(SingletonComponent.java:122)
        at org.jboss.as.ejb3.component.singleton.SingletonComponent.start(SingletonComponent.java:137)
        at org.jboss.as.ee.component.ComponentStartService$1.run(ComponentStartService.java:54) [wildfly-ee-8.1.0.Final.jar:8.1.0.Final]
        ... 6 more
Caused by: javax.ejb.EJBException: javax.enterprise.inject.CreationException
        at org.jboss.as.ejb3.tx.CMTTxInterceptor.handleExceptionInOurTx(CMTTxInterceptor.java:190)
        at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:275)
        at org.jboss.as.ejb3.tx.CMTTxInterceptor.requiresNew(CMTTxInterceptor.java:369)
        at org.jboss.as.ejb3.tx.LifecycleCMTTxInterceptor.processInvocation(LifecycleCMTTxInterceptor.java:66)
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:309) [jboss-invocation-1.2.1.Final.jar:1.2.1.Final]
        at org.jboss.as.weld.injection.WeldInjectionContextInterceptor.processInvocation(WeldInjectionContextInterceptor.java:43)
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:309) [jboss-invocation-1.2.1.Final.jar:1.2.1.Final]
        at org.jboss.as.ejb3.component.interceptors.CurrentInvocationContextInterceptor.processInvocation(CurrentInvocationContextInterceptor.java:41)
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:309) [jboss-invocation-1.2.1.Final.jar:1.2.1.Final]
        at org.jboss.as.ee.concurrent.ConcurrentContextInterceptor.processInvocation(ConcurrentContextInterceptor.java:45) [wildfly-ee-8.1.0.Final.jar:8.1.0.Final]
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:309) [jboss-invocation-1.2.1.Final.jar:1.2.1.Final]
        at org.jboss.invocation.ContextClassLoaderInterceptor.processInvocation(ContextClassLoaderInterceptor.java:64) [jboss-invocation-1.2.1.Final.jar:1.2.1.Final]
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:309) [jboss-invocation-1.2.1.Final.jar:1.2.1.Final]
        at org.jboss.invocation.InterceptorContext.run(InterceptorContext.java:326) [jboss-invocation-1.2.1.Final.jar:1.2.1.Final]
        at org.jboss.invocation.PrivilegedWithCombinerInterceptor.processInvocation(PrivilegedWithCombinerInterceptor.java:80) [jboss-invocation-1.2.1.Final.jar:1.2.1.Final]
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:309) [jboss-invocation-1.2.1.Final.jar:1.2.1.Final]
        at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61) [jboss-invocation-1.2.1.Final.jar:1.2.1.Final]
        at org.jboss.as.ee.component.BasicComponent.constructComponentInstance(BasicComponent.java:160) [wildfly-ee-8.1.0.Final.jar:8.1.0.Final]
        ... 11 more
Caused by: javax.enterprise.inject.CreationException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [rt.jar:1.8.0_45]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [rt.jar:1.8.0_45]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [rt.jar:1.8.0_45]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422) [rt.jar:1.8.0_45]
        at java.lang.Class.newInstance(Class.java:442) [rt.jar:1.8.0_45]
        at org.jboss.weld.security.NewInstanceAction.run(NewInstanceAction.java:33)
        at java.security.AccessController.doPrivileged(Native Method) [rt.jar:1.8.0_45]
        at org.jboss.weld.injection.Exceptions.rethrowException(Exceptions.java:40)
        at org.jboss.weld.injection.Exceptions.rethrowException(Exceptions.java:50)
        at org.jboss.weld.injection.Exceptions.rethrowException(Exceptions.java:54)
        at org.jboss.weld.injection.FieldInjectionPoint.inject(FieldInjectionPoint.java:96)
        at org.jboss.weld.util.Beans.injectBoundFields(Beans.java:358)
        at org.jboss.weld.util.Beans.injectFieldsAndInitializers(Beans.java:369)
        at org.jboss.weld.injection.producer.DefaultInjector.inject(DefaultInjector.java:72)
        at org.jboss.weld.injection.producer.DefaultInjector$1.proceed(DefaultInjector.java:66)
        at org.jboss.weld.injection.InjectionContextImpl.run(InjectionContextImpl.java:48)
        at org.jboss.weld.injection.producer.DefaultInjector.inject(DefaultInjector.java:64)
        at org.jboss.weld.injection.producer.BasicInjectionTarget.inject(BasicInjectionTarget.java:90)
        at org.jboss.as.weld.injection.WeldInjectionContext.inject(WeldInjectionContext.java:39)
        at org.jboss.as.weld.injection.WeldInjectionInterceptor.processInvocation(WeldInjectionInterceptor.java:51)
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:309) [jboss-invocation-1.2.1.Final.jar:1.2.1.Final]
        at org.jboss.as.ee.component.AroundConstructInterceptorFactory$1.processInvocation(AroundConstructInterceptorFactory.java:28) [wildfly-ee-8.1.0.Final.jar:8.1.0.Final]
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:309) [jboss-invocation-1.2.1.Final.jar:1.2.1.Final]
        at org.jboss.as.weld.injection.WeldInterceptorInjectionInterceptor.processInvocation(WeldInterceptorInjectionInterceptor.java:56)
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:309) [jboss-invocation-1.2.1.Final.jar:1.2.1.Final]
        at org.jboss.as.weld.ejb.Jsr299BindingsCreateInterceptor.processInvocation(Jsr299BindingsCreateInterceptor.java:93)
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:309) [jboss-invocation-1.2.1.Final.jar:1.2.1.Final]
        at org.jboss.as.ee.component.NamespaceContextInterceptor.processInvocation(NamespaceContextInterceptor.java:50) [wildfly-ee-8.1.0.Final.jar:8.1.0.Final]
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:309) [jboss-invocation-1.2.1.Final.jar:1.2.1.Final]
        at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:273)
        ... 27 more
Caused by: javax.naming.NameNotFoundException: picketlink/JPADSBasedPartitionManager -- service jboss.naming.context.java.picketlink.JPADSBasedPartitionManager
        at org.jboss.as.naming.ServiceBasedNamingStore.lookup(ServiceBasedNamingStore.java:104) [wildfly-naming-8.1.0.Final.jar:8.1.0.Final]
        at org.jboss.as.naming.NamingContext.lookup(NamingContext.java:202) [wildfly-naming-8.1.0.Final.jar:8.1.0.Final]
        at org.jboss.as.naming.InitialContext$DefaultInitialContext.lookup(InitialContext.java:233) [wildfly-naming-8.1.0.Final.jar:8.1.0.Final]
        at org.jboss.as.naming.NamingContext.lookup(NamingContext.java:188) [wildfly-naming-8.1.0.Final.jar:8.1.0.Final]
        at org.jboss.as.naming.NamingContext.lookup(NamingContext.java:184) [wildfly-naming-8.1.0.Final.jar:8.1.0.Final]
        at javax.naming.InitialContext.lookup(InitialContext.java:417) [rt.jar:1.8.0_45]
        at javax.naming.InitialContext.lookup(InitialContext.java:417) [rt.jar:1.8.0_45]
        at org.jboss.as.weld.services.bootstrap.WeldResourceInjectionServices.resolveResource(WeldResourceInjectionServices.java:186)
        at org.jboss.as.weld.services.bootstrap.WeldResourceInjectionServices$1.createResource(WeldResourceInjectionServices.java:139)
        at org.jboss.weld.injection.AbstractResourceInjection.getResourceReference(AbstractResourceInjection.java:44)
        at org.jboss.weld.injection.AbstractResourceInjection.injectResourceReference(AbstractResourceInjection.java:53)
        at org.jboss.weld.util.Beans.injectEEFields(Beans.java:331)
        at org.jboss.weld.injection.producer.ResourceInjector.inject(ResourceInjector.java:59)
        at org.jboss.weld.injection.producer.DefaultInjector$1.proceed(DefaultInjector.java:66)
        at org.jboss.weld.injection.InjectionContextImpl.run(InjectionContextImpl.java:48)
        at org.jboss.weld.injection.producer.DefaultInjector.inject(DefaultInjector.java:64)
        at org.jboss.weld.injection.producer.BasicInjectionTarget.inject(BasicInjectionTarget.java:90)
        at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:150)
        at org.jboss.weld.context.unbound.DependentContextImpl.get(DependentContextImpl.java:69)
        at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:733)
        at org.jboss.weld.injection.producer.AbstractMemberProducer.getReceiver(AbstractMemberProducer.java:128)
        at org.jboss.weld.injection.producer.AbstractMemberProducer.produce(AbstractMemberProducer.java:148)
        at org.jboss.weld.bean.AbstractProducerBean.create(AbstractProducerBean.java:183)
        at org.jboss.weld.bean.builtin.ee.EEResourceProducerField.createUnderlying(EEResourceProducerField.java:144)
        at org.jboss.weld.bean.builtin.ee.EEResourceProducerField.create(EEResourceProducerField.java:133)
        at org.jboss.weld.context.unbound.DependentContextImpl.get(DependentContextImpl.java:69)
        at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:733)
        at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:753)
        at org.jboss.weld.bean.builtin.InstanceImpl.getBeanInstance(InstanceImpl.java:86)
        at org.jboss.weld.bean.builtin.InstanceImpl.get(InstanceImpl.java:76)
        at org.picketlink.producer.IdentityManagerProducer.init(IdentityManagerProducer.java:102)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_45]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_45]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_45]
        at java.lang.reflect.Method.invoke(Method.java:497) [rt.jar:1.8.0_45]
        at org.jboss.weld.injection.MethodInjectionPoint.invokeWithSpecialValue(MethodInjectionPoint.java:72)
        at org.jboss.weld.injection.MethodInjectionPoint.invoke(MethodInjectionPoint.java:66)
        at org.jboss.weld.util.Beans.callInitializers(Beans.java:382)
        at org.jboss.weld.util.Beans.injectFieldsAndInitializers(Beans.java:370)
        at org.jboss.weld.injection.producer.DefaultInjector.inject(DefaultInjector.java:72)
        at org.jboss.weld.injection.producer.ResourceInjector.inject(ResourceInjector.java:60)
        at org.jboss.weld.injection.producer.DefaultInjector$1.proceed(DefaultInjector.java:66)
        at org.jboss.weld.injection.InjectionContextImpl.run(InjectionContextImpl.java:48)
        at org.jboss.weld.injection.producer.DefaultInjector.inject(DefaultInjector.java:64)
        at org.jboss.weld.injection.producer.BasicInjectionTarget.inject(BasicInjectionTarget.java:90)
        at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:150)
        at org.jboss.weld.context.AbstractContext.get(AbstractContext.java:96)
        at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:733)
        at org.jboss.weld.injection.producer.AbstractMemberProducer.getReceiver(AbstractMemberProducer.java:128)
        at org.jboss.weld.injection.producer.AbstractMemberProducer.produce(AbstractMemberProducer.java:148)
        at org.jboss.weld.bean.AbstractProducerBean.create(AbstractProducerBean.java:183)
        at org.jboss.weld.context.unbound.DependentContextImpl.get(DependentContextImpl.java:69)
        at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:733)
        at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:789)
        at org.jboss.weld.injection.FieldInjectionPoint.inject(FieldInjectionPoint.java:92)
        ... 46 more

23:48:57,647 ERROR [org.jboss.as.controller.management-operation] (management-handler-thread - 1) JBAS014613: Operation ("deploy") failed - address: ([("deployment" => "picketlink-authorization-idm-jpa-with-subsystem.war")]) - failure description: {"JBAS014671: Failed services" => {"jboss.deployment.unit.\"picketlink-authorization-idm-jpa-with-subsystem.war\".component.SecurityInitializer.START" => "org.jboss.msc.service.StartException in service jboss.deployment.unit.\"picketlink-authorization-idm-jpa-with-subsystem.war\".component.SecurityInitializer.START: java.lang.IllegalStateException: JBAS011048: Failed to construct component instance
    Caused by: java.lang.IllegalStateException: JBAS011048: Failed to construct component instance
    Caused by: javax.ejb.EJBException: javax.enterprise.inject.CreationException
    Caused by: javax.enterprise.inject.CreationException
    Caused by: javax.naming.NameNotFoundException: picketlink/JPADSBasedPartitionManager -- service jboss.naming.context.java.picketlink.JPADSBasedPartitionManager"}}
23:48:57,651 ERROR [org.jboss.as.server] (management-handler-thread - 1) JBAS015870: Deploy of deployment "picketlink-authorization-idm-jpa-with-subsystem.war" was rolled back with the following failure message:
{"JBAS014671: Failed services" => {"jboss.deployment.unit.\"picketlink-authorization-idm-jpa-with-subsystem.war\".component.SecurityInitializer.START" => "org.jboss.msc.service.StartException in service jboss.deployment.unit.\"picketlink-authorization-idm-jpa-with-subsystem.war\".component.SecurityInitializer.START: java.lang.IllegalStateException: JBAS011048: Failed to construct component instance
    Caused by: java.lang.IllegalStateException: JBAS011048: Failed to construct component instance
    Caused by: javax.ejb.EJBException: javax.enterprise.inject.CreationException
    Caused by: javax.enterprise.inject.CreationException
    Caused by: javax.naming.NameNotFoundException: picketlink/JPADSBasedPartitionManager -- service jboss.naming.context.java.picketlink.JPADSBasedPartitionManager"}}
23:48:57,663 INFO  [org.jboss.weld.deployer] (MSC service thread 1-8) JBAS016009: Stopping weld service for deployment picketlink-authorization-idm-jpa-with-subsystem.war
23:48:57,677 INFO  [org.jboss.as.connector.subsystems.datasources] (MSC service thread 1-4) JBAS010409: Unbound data source [java:jboss/datasources/PicketLinkQuickstartDS]
23:48:58,019 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-15) JBAS015877: Stopped deployment picketlink-authorization-idm-jpa-with-subsystem.war (runtime-name: picketlink-authorization-idm-jpa-with-subsystem.war) in 367ms 23:48:58,023 INFO  [org.jboss.as.controller] (management-handler-thread - 1) JBAS014774: Service status report
JBAS014775:    New missing/unsatisfied dependencies:
      service jboss.deployment.unit."picketlink-authorization-idm-jpa-with-subsystem.war".WeldBootstrapService (missing) dependents: [service jboss.undertow.deployment.default-server.default-host./picketlink-authorization-idm-jpa-with-subsystem.UndertowDeploymentInfoService, service jboss.undertow.deployment.default-server.default-host./picketlink-authorization-idm-jpa-with-subsystem]
      service jboss.deployment.unit."picketlink-authorization-idm-jpa-with-subsystem.war".WeldStartService (missing) dependents: [service jboss.undertow.deployment.default-server.default-host./picketlink-authorization-idm-jpa-with-subsystem.UndertowDeploymentInfoService]
      service jboss.deployment.unit."picketlink-authorization-idm-jpa-with-subsystem.war".component.AuthorizationChecker.START (missing) dependents: [service jboss.undertow.deployment.default-server.default-host./picketlink-authorization-idm-jpa-with-subsystem.UndertowDeploymentInfoService, service jboss.undertow.deployment.default-server.default-host./picketlink-authorization-idm-jpa-with-subsystem, service jboss.deployment.unit."picketlink-authorization-idm-jpa-with-subsystem.war".moduleDeploymentRuntimeInformationStart]
      service jboss.deployment.unit."picketlink-authorization-idm-jpa-with-subsystem.war".component.LoginController.START (missing) dependents: [service jboss.undertow.deployment.default-server.default-host./picketlink-authorization-idm-jpa-with-subsystem.UndertowDeploymentInfoService, service jboss.undertow.deployment.default-server.default-host./picketlink-authorization-idm-jpa-with-subsystem, service jboss.deployment.unit."picketlink-authorization-idm-jpa-with-subsystem.war".moduleDeploymentRuntimeInformationStart, service jboss.deployment.unit."picketlink-authorization-idm-jpa-with-subsystem.war".deploymentCompleteService]
      service jboss.deployment.unit."picketlink-authorization-idm-jpa-with-subsystem.war".component.SecurityInitializer.START (missing) dependents: [service jboss.undertow.deployment.default-server.default-host./picketlink-authorization-idm-jpa-with-subsystem.UndertowDeploymentInfoService, service jboss.undertow.deployment.default-server.default-host./picketlink-authorization-idm-jpa-with-subsystem, service jboss.deployment.unit."picketlink-authorization-idm-jpa-with-subsystem.war".moduleDeploymentRuntimeInformationStart]
      service jboss.deployment.unit."picketlink-authorization-idm-jpa-with-subsystem.war".component."com.sun.faces.config.ConfigureListener".START (missing) dependents: [service jboss.undertow.deployment.default-server.default-host./picketlink-authorization-idm-jpa-with-subsystem.UndertowDeploymentInfoService, service jboss.undertow.deployment.default-server.default-host./picketlink-authorization-idm-jpa-with-subsystem, service jboss.deployment.unit."picketlink-authorization-idm-jpa-with-subsystem.war".deploymentCompleteService]
      service jboss.deployment.unit."picketlink-authorization-idm-jpa-with-subsystem.war".component."javax.faces.webapp.FacetTag".START (missing) dependents: [service jboss.undertow.deployment.default-server.default-host./picketlink-authorization-idm-jpa-with-subsystem.UndertowDeploymentInfoService, service jboss.undertow.deployment.default-server.default-host./picketlink-authorization-idm-jpa-with-subsystem]
      service jboss.deployment.unit."picketlink-authorization-idm-jpa-with-subsystem.war".component."javax.servlet.jsp.jstl.tlv.PermittedTaglibsTLV".START (missing) dependents: [service jboss.undertow.deployment.default-server.default-host./picketlink-authorization-idm-jpa-with-subsystem.UndertowDeploymentInfoService, service jboss.undertow.deployment.default-server.default-host./picketlink-authorization-idm-jpa-with-subsystem, service jboss.deployment.unit."picketlink-authorization-idm-jpa-with-subsystem.war".deploymentCompleteService]
      service jboss.deployment.unit."picketlink-authorization-idm-jpa-with-subsystem.war".component."javax.servlet.jsp.jstl.tlv.ScriptFreeTLV".START (missing) dependents: [service jboss.undertow.deployment.default-server.default-host./picketlink-authorization-idm-jpa-with-subsystem.UndertowDeploymentInfoService, service jboss.undertow.deployment.default-server.default-host./picketlink-authorization-idm-jpa-with-subsystem, service jboss.deployment.unit."picketlink-authorization-idm-jpa-with-subsystem.war".deploymentCompleteService]
      service jboss.deployment.unit."picketlink-authorization-idm-jpa-with-subsystem.war".component."org.jboss.weld.servlet.WeldInitialListener".START (missing) dependents: [service jboss.undertow.deployment.default-server.default-host./picketlink-authorization-idm-jpa-with-subsystem.UndertowDeploymentInfoService, service jboss.undertow.deployment.default-server.default-host./picketlink-authorization-idm-jpa-with-subsystem]
      service jboss.deployment.unit."picketlink-authorization-idm-jpa-with-subsystem.war".component."org.jboss.weld.servlet.WeldTerminalListener".START (missing) dependents: [service jboss.undertow.deployment.default-server.default-host./picketlink-authorization-idm-jpa-with-subsystem.UndertowDeploymentInfoService, service jboss.undertow.deployment.default-server.default-host./picketlink-authorization-idm-jpa-with-subsystem]
      service jboss.deployment.unit."picketlink-authorization-idm-jpa-with-subsystem.war".ee.ComponentRegistry (missing) dependents: [service jboss.undertow.deployment.default-server.default-host./picketlink-authorization-idm-jpa-with-subsystem.UndertowDeploymentInfoService]
      service jboss.deployment.unit."picketlink-authorization-idm-jpa-with-subsystem.war".moduleDeploymentRuntimeInformation (missing) dependents: [service jboss.deployment.unit."picketlink-authorization-idm-jpa-with-subsystem.war".moduleDeploymentRuntimeInformationStart]
      service jboss.undertow.deployment.default-server.default-host./picketlink-authorization-idm-jpa-with-subsystem.UndertowDeploymentInfoService (missing) dependents: [service jboss.undertow.deployment.default-server.default-host./picketlink-authorization-idm-jpa-with-subsystem]
      service jboss.undertow.deployment.default-server.default-host./picketlink-authorization-idm-jpa-with-subsystem.codec (missing) dependents: [service jboss.undertow.deployment.default-server.default-host./picketlink-authorization-idm-jpa-with-subsystem.UndertowDeploymentInfoService]
JBAS014777:   Services which failed to start:      service jboss.deployment.unit."picketlink-authorization-idm-jpa-with-subsystem.war".component.SecurityInitializer.START
</pre>

**Comment by twimnox** [comment]
Any solutions for this?

**Comment by arunpravin07** [comment]
sry bruh
